---
- hosts: all
  vars:
    jenkins_master_nginx_proxy: true
    jenkins_master_nginx_unlink_default: true
    jenkins_master_nginx_server_name: "bogus.fogbutter.com"
    jenkins_master_nginx_ssl: true
    jenkins_master_nginx_ssl_s3_bucket: "fogbutter-development-support"
    jenkins_master_nginx_ssl_s3_crt: "self-signed-mock-ssl/bogus.fogbutter.com.crt"
    jenkins_master_nginx_ssl_s3_key: "self-signed-mock-ssl/bogus.fogbutter.com.key"
    jenkins_master_nginx_ssl_s3_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    jenkins_master_nginx_ssl_s3_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
  roles: [./]
