---
- name: add public key for jenkins apt repository
  become: yes
  become_method: sudo
  apt_key: url={{ jenkins_master_apt_key_url }} state=present id={{ jenkins_master_apt_key_id }}
  tags: [jenkins-master-install]

- name: add jenkins apt repository
  become: yes
  become_method: sudo
  apt_repository: repo="{{ jenkins_master_apt_repo }}" update_cache=yes
  tags: [jenkins-master-install]

- name: install required packages
  become: yes
  become_method: sudo
  apt: name=jenkins state=present
  tags: [jenkins-master-install]

- name: ensure jenkins service is enabled and running
  become: yes
  become_method: sudo
  service: name=jenkins state=started enabled=true
  tags: [jenkins-master-install]
